ignore-workspace-root-check: true
packages:
  - 'codegen/results'
  - 'src/*'
  - 'src/platforms/*'
  - 'src/forks/*'

   # We don't care about devDependencies for these forks:
  - '!src/forks/solito'
