# Some direction & snippets taken from https://github.com/thomasread99/expo-workflows/

on:
    workflow_dispatch:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: false
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: false
          default: 'production'
    workflow_call:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: true
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: true
          default: 'production'

jobs:
  build:
    strategy:
      matrix: ${{ fromJson( inputs.platform ) }}
    name: Build App (${{ matrix.platform }})
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:

        - run: echo ${{inputs.platform}}

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4
          with:
              version: 9


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install dependencies
          run: pnpm install --frozen-lockfile


        - name: Run Codegen
          run: pnpm run codegen

        # =============================
        #    Workflow-Specific Stuff
        # =============================


        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
            packager: pnpm

        - name: "DEBUG: `eas whoami`" # Yes, the above does supposedly work. See https://docs.github.com/en/actions/learn-github-actions/contexts#runner-context
          if: runner.debug == '1'
          run: eas whoami



        # ==== [ANDROID] Set up JDK & Android Studio ====

        - name: Set up JDK 17
          if: matrix.platform == 'android'
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'gradle'

        - name: Setup Android SDK
          if: matrix.platform == 'android'
          uses: android-actions/setup-android@v3


        # ==== Build App ====

        - name: Build App for ${{ matrix.platform }}
          run: pnpm run build-expo-NEEDS-PLATFORM --platform=${{ matrix.platform }} --profile=${{ inputs.profile }} --output=build/${{ matrix.platform }}


        # ==== Upload Artifact ====

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: "native-${{ matrix.platform }}"
            path: build/${{ matrix.platform }}
