name: Build / Next.js Site

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4


        - name: Load Example ENV File
          uses: duskmoon314/action-load-env@v1
          id: load-env
          with:
            files: |
              .env.example


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Cache Supabase CLI Docker Images
          uses: ScribeMD/docker-cache@0.5.0
          with:
            key: supabase-cli-${{ runner.os }}


        - name: Install Dependencies & Run Codegen
          run: pnpm install --frozen-lockfile
          shell: pwsh


        # =============================
        #    Workflow-Specific Stuff
        # =============================

        - name: "Restore Cache: Next.js Build"
          uses: actions/cache/restore@v4
          with:
            path: ${{ github.workspace }}/src/platfrms/next/.next/cache
            # Generate a new cache whenever packages or source files change.
            key: nextjs-${{ hashFiles('src/pnpm-lock.json') }}-${{ hashFiles('src/**/*.js', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.tsx') }}
            # If source files changed but packages didn't, rebuild from a prior cache.
            restore-keys: nextjs-${{ hashFiles('src/pnpm-lock.json') }}

        - name: "DEBUG: Log Entire Directory Tree"
          if: runner.debug == '1'
          run: tree
          shell: pwsh

        - name: Build Next.js Site
          run: pwsh scripts/build-nextjs-site.ps1
          shell: pwsh

        - name: "Cache: Next.js Build"
          uses: actions/cache/save@v4
          with:
            path: ${{ github.workspace }}/src/platfrms/next/.next/cache
            key: nextjs-${{ hashFiles('src/pnpm-lock.json') }}-${{ hashFiles('src/**/*.js', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.tsx') }}

        - name: Upload Docker Compose Artifact
          uses: actions/upload-artifact@v4
          with:
            name: site-docker-compose
            path: dist/web-server
            include-hidden-files: true
            if-no-files-found: error

        - name: Save Docker Images
          run: pwsh scripts/save-nextjs-images.ps1
          shell: pwsh

        - name: Upload Docker Images
          uses: actions/upload-artifact@v4
          with:
            name: site-docker-images
            path: dist/web-server-images.tar
            include-hidden-files: true
            if-no-files-found: error
