name: Build / Expo App

# Some direction & snippets taken from https://github.com/thomasread99/expo-workflows/

on:
    workflow_dispatch:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: false
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: false
          default: 'production'
    workflow_call:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: true
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: true
          default: 'production'

jobs:
  build:
    strategy:
      matrix: ${{ fromJson( inputs.platform ) }}
    name: Build App (${{ matrix.platform }})
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:

        - run: echo ${{inputs.platform}}

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4


        - name: Load Example ENV File
          uses: duskmoon314/action-load-env@v1
          id: load-env
          with:
            files: |
              .env.example


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        # Tried caching Docker images, but doing so maed it slightly slower---not faster.
        # And when the images update, it tacks another minute onto the end of the job.


        - name: Install Dependencies & Run Codegen
          run: pnpm install --frozen-lockfile
          shell: pwsh


        # =============================
        #    Workflow-Specific Stuff
        # =============================


        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
            packager: pnpm

        - name: "DEBUG: `eas whoami`"
          if: runner.debug == '1'
          run: eas whoami
          shell: pwsh



        # ==== [ANDROID] Set up JDK & Android Studio ====

        - name: Set up JDK 17
          if: matrix.platform == 'android'
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'gradle'

        - name: Setup Android SDK
          if: matrix.platform == 'android'
          uses: android-actions/setup-android@v3


        # TODO: Set up Xcode for iOS


        # ==== Build App ====

        - name: Get File Extension
          id: get-file-extension
          run: |
            $extension = if ($env:PLATFORM -eq 'ios') { '.ipa' } else { node -e "console.log(require('./src/platforms/expo/eas.json').build.${{ inputs.profile }}.android.buildType)" }
            if ($extension -eq 'app-bundle') { $extension = '.aab' }
            echo "extension=$extension" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          shell: pwsh

        - name: Build App for ${{ matrix.platform }}
          run: 'pnpm run build-expo-NEEDS-PLATFORM --platform=${{ matrix.platform }} --profile=${{ inputs.profile }} --message="GitHub Actions: ${{ github.sha }} (#${{ github.run_id }})" --output=../../../dist/expo-app-${{ matrix.platform }}${{ env.extension }}'
          shell: pwsh


        # ==== Upload Artifact ====

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: "expo-app-${{ matrix.platform }}"
            path: dist/expo-app-${{ matrix.platform }}.${{ env.extension }}
            if-no-files-found: error
