on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          shell: pwsh


        # =============================
        #    Workflow-Specific Stuff
        # =============================

        # TODO: Migrate this to a Docker build rather than a regular-ol Next.js build

        - uses: actions/cache@v4
          with:
            path: ${{ github.workspace }}/src/platfrms/next/.next/cache
            # Generate a new cache whenever packages or source files change.
            key: nextjs-${{ hashFiles('src/pnpm-lock.json') }}-${{ hashFiles('src/**/*.js', 'src/**/*.jsx', 'src/**/*.ts', 'src/**/*.tsx') }}
            # If source files changed but packages didn't, rebuild from a prior cache.
            restore-keys: nextjs-${{ hashFiles('src/pnpm-lock.json') }}

        - name: Build Next.js Site
          working-directory: src/platforms/next
          run: pnpm run build
          shell: pwsh

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: site
            path: src/platforms/next/out
