on:
    workflow_dispatch:
    push:
        paths:
            - package.json
            - pnpm-lock.yaml
            - codegen.js
            - tsconfig.json
            - turbo.json
            - utilityTypes.ts
            - schema.prisma
            - src/forks/**
            - src/interface/**
            - src/lib/**
            - src/platforms/next/**
            - config/**
            - assets/**
            - .github/workflows/build-app.yaml

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                  node-version: 14.x
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
            - name: Test
              run: pnpm test
            - name: Generate Prisma Client
              run: pnpm prisma generate
            - name: Generate GraphQL Types
              run: pnpm codegen
            - name: Deploy
              run: pnpm deploy
