on:
    workflow_dispatch:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: false
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: false
          default: 'production'
    workflow_call:
      inputs:
        platform:
          type: string
          description: 'Platforms to build for, defined as {platform: ["ios", "android", "futurePhone(TM)"]} because Actions forgot what an array is'
          required: true
          default: '{"platform": ["ios", "android"]}'
        profile:
          type: string
          description: 'Build profile'
          required: true
          default: 'production'

jobs:
  build:
    strategy:
      matrix: ${{ fromJson( inputs.platform ) }}
    name: Build App (${{ matrix.platform }})
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:

        - run: echo ${{inputs.platform}}

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4
          with:
              version: 9


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install dependencies
          run: pnpm install --frozen-lockfile


        - name: Run Codegen
          run: pnpm run codegen

        # =============================
        #    Workflow-Specific Stuff
        # =============================


        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
            packager: pnpm

        - name: "DEBUG: `eas whoami`"
          run: eas whoami

        - name: Run `git init` Because Expo Is Silly
          run: git init
          working-directory: ${{ github.workspace }}

        - name: Build App for ${{ matrix.platform }}
          run: pnpm run build-expo-NEEDS-PLATFORM --platform=${{ matrix.platform }} --profile=${{ inputs.profile }} --output=build/${{ matrix.platform }}

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: "native-${{ matrix.platform }}"
            path: build/${{ matrix.platform }}
