on:
  workflow_dispatch:
  push:
      paths:
          - package.json
          - pnpm-lock.yaml
          - codegen.js
          - tsconfig.json
          - turbo.json
          - utilityTypes.ts
          - schema.prisma
          - src/forks/**
          - src/interface/**
          - src/lib/**
          - src/platforms/next/**
          - config/**
          - assets/**
          - .github/workflows/build-app.yaml





jobs:
  test:
    runs-on: ubuntu-latest
    steps:

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4
          with:
              version: 9


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        # =============================
        #    Workflow-Specific Stuff
        # =============================

        - name: Run Tests
          run: pnpm test
