name: Run Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .gitignore
      - LICENSE.md
      - readme.md
      - todo.md
      - .vscode





jobs:
  tests-code:
    name: Code Tests
    runs-on: ubuntu-latest
    steps:

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4


        - name: Load Example ENV File
          uses: duskmoon314/action-load-env@v1
          id: load-env
          with:
            files: |
              .env.example


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install Dependencies & Run Codegen
          run: pnpm install --frozen-lockfile


        # =============================
        #    Workflow-Specific Stuff
        # =============================

        - name: Run Code Tests
          run: pnpm test-code


  build-expo:
    name: Build / Mobile
    needs: tests-code
    uses: ./.github/workflows/build-expo.yaml
    with:
      platform: '["ios","android"]'
      profile: preview


  build-next:
    name: Build / Web
    needs: tests-code
    uses: ./.github/workflows/build-next.yaml


  test-end-to-end:
    name: End-to-End Tests
    needs: [build-expo, build-next]
    runs-on: ubuntu-latest
    steps:

        # ============================
        #        Project Setup
        # ============================

        - name: Clone Repo
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'


        - name: Set Up PNPM
          uses: pnpm/action-setup@v4
          with:
              version: 9


        - name: Set Up Node.js 21
          uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'pnpm'


        - name: Install dependencies
          run: pnpm install --frozen-lockfile
          shell: pwsh


        # =============================
        #    Workflow-Specific Stuff
        # =============================

        - name: Download Artifacts
          uses: actions/download-artifact@v4

        - name: Run End-to-End Tests
          run: pnpm test-e2e
